# Generated by Django 4.2.2 on 2023-06-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_courscsharp_coursdart_coursjava_coursjavascript_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursphp",
            options={},
        ),
        migrations.AlterField(
            model_name="coursphp",
            name="resultat",
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="coursphp",
            name="title",
            field=models.TextField(max_length=500),
        ),
    ]
