# Generated by Django 4.2.2 on 2023-07-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_coursphp_code_alter_coursphp_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoryjavas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="article",
        ),
    ]
