# Generated by Django 4.2.2 on 2023-07-01 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_categoryjavas_delete_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursjavascript",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.categoryjavas",
            ),
        ),
    ]
