# Generated by Django 4.2.2 on 2023-07-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_coursjavascript_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courscsharp",
            name="code",
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="courscsharp",
            name="resultat",
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="coursjava",
            name="code",
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="coursjava",
            name="resultat",
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="coursjavascript",
            name="code",
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="coursjavascript",
            name="resultat",
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="courspython",
            name="resultat",
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="courspython",
            name="title",
            field=models.TextField(max_length=500),
        ),
    ]
