# Generated by Django 4.2.2 on 2023-07-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_courscsharp_code_alter_courscsharp_resultat_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursdart",
            options={"ordering": ["date_added"]},
        ),
        migrations.AlterModelOptions(
            name="coursjava",
            options={"ordering": ["date_added"]},
        ),
        migrations.AlterModelOptions(
            name="coursjavascript",
            options={"ordering": ["date_added"]},
        ),
        migrations.AlterModelOptions(
            name="coursphp",
            options={"ordering": ["date_added"]},
        ),
        migrations.AlterModelOptions(
            name="courspython",
            options={"ordering": ["date_added"]},
        ),
        migrations.AddField(
            model_name="blog",
            name="full_description",
            field=models.TextField(default=1, max_length=500000),
            preserve_default=False,
        ),
    ]
