# Generated by Django 4.2.2 on 2023-07-01 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_categorydart_coursdart_categorie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursdart",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.categorydart",
            ),
        ),
    ]
