# Generated by Django 4.2.2 on 2023-07-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_categoryjava_categoryphp_coursjava_categorie_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='phpcourse',
        ),
    ]
