# Generated by Django 4.2.2 on 2023-07-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_categorycsharp_courscsharp_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courspython",
            name="code",
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name="courspython",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
