# Generated by Django 4.2.2 on 2023-07-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_alter_courspython_code_alter_courspython_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="full_description",
            field=models.TextField(max_length=50000000),
        ),
    ]
